#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# Info: https://linuxhint.com/bash-while-loop-examples/

# Initialize counter

i=1

while [ $i -le 10 ]
do
	echo "Best School"
	(( i=i+1 ))
done
