#!/usr/bin/env bash
# This script is displaying "Best School" 10 times with an if statement

# Initialize counter

i=0

while [ $i -lt 11 ]
do
	if [ $i -eq 9 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
        ((i++))
done
